//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPFChocolate.ApplicationData
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int ID { get; set; }
        public int IDUser { get; set; }
        public int IDProduct { get; set; }
        public System.DateTime Date { get; set; }
        public int Count { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
